version: "3"

volumes:
  caddy-config:
    name: caddy-config
    driver: local
  caddy-data:
    name: caddy-data
    driver: local

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge
    external: true

services:
  whoami:
    image: docker.io/traefik/whoami:latest
    init: true
    container_name: whoami
    restart: unless-stopped
    networks:
      - reverse-proxy
    expose:
      - 80
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
        compress: "true"
  caddy:
    image: docker.io/library/caddy:2.3.0-alpine
    init: true
    container_name: caddy
    restart: unless-stopped
    networks:
      - reverse-proxy
    expose:
      - ${ENV_HTTP_PORT}
      - ${ENV_HTTPS_PORT}
    ports:
      - ${ENV_HTTP_PORT}:${ENV_HTTP_PORT}
      - ${ENV_HTTPS_PORT}:${ENV_HTTPS_PORT}
    environment:
      - DOMAIN=${ENV_DOMAIN}
      - EMAIL=${ENV_EMAIL}
    volumes:
      - caddy-config:/config:rw
      - caddy-data:/data:rw
      - ./Caddyfile:/etc/caddy/Caddyfile:rw
    command: [ "/usr/bin/caddy", "run", "--adapter", "caddyfile", "--config", "/etc/caddy/Caddyfile", "--watch" ]
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
        compress: "true"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --spider --tries=1 https://health.${ENV_DOMAIN}/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
