version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"

volumes:
  caddy_data:
    external: true
  caddy_config:
    name: caddy_config
    driver: local

networks:
  reverse_proxy:
    name: reverse_proxy
    driver: bridge
    external: true

services:
  caddy:
    <<: *basic-setting
    image: docker.io/library/caddy:2-alpine
    container_name: caddy
    networks:
      - reverse_proxy
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${ENV_DOMAIN}
      - EMAIL=${ENV_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./conf.d:/etc/caddy/conf.d:ro
      - caddy_data:/data:rw
      - caddy_config:/config:rw
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --spider --tries=1 https://health.${ENV_DOMAIN}/ || exit 1" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3
  whoami:
    <<: *basic-setting
    image: docker.io/traefik/whoami:latest
    container_name: whoami
    networks:
      - reverse_proxy
    expose:
      - 80
